language: java
node_js:
  - "10.9.0"
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - graphhopper
  - map-matching
  - graph-cache
  - osrm
  - tcat-ny-us
before_install:
  - command -v mvn
  - command -v wget
  - command -v npm
  - command -v java
  - command -v tar
install:
  - npm run setup
script:
  - npm run travis