language: java
services:
- docker
node_js:
- 10.9.0
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - graphhopper
  - map-matching
  - graph-cache
  - osrm
  - tcat-ny-us
  - node_modules
  - cache
install:
- docker-compose -f docker-compose/docker-compose.yml up
script:
- npm run travis
env:
  secure: k61nn7b/tQ+dvNS9IMKM0gYWXPIY48RuwslOM6bSCWri9803oohASpP0FR/Ayo3JLXxywpIWBPfgjbEVCbjDQkovd3pkS8xT1e0N7zim25yiFMxZricEYoH3OhUMWUvaG71iClXaCk4RXDs8JVQ+mEY4+RlMytIfnuuqD/R+qA7o0HSR7ytSrGy2zGraXaf4lFOCNif8K5luzX4ZeiWpUVhqiw+2HhrqS8Fy24+ukAIN9a7xb2T1lc/LuHXkwyBkx35/dAGPEezvnPW6N95O/myDbuZTYycjA8Qh/Lht/+qSKaL9hTP5mer1pI+eoEpVvo6dCShr/1sTyIDuZyC3uYxFzlKWfkXbbzrOQ1HkOpeah4q5+h7ngj/XefCunzpzCW8DpZfuWG3AZRQaT1XoYAH5HpM328TSqxotyrbCRLp8AfXQoql0MOZS46vYYNY0BQb4Vw7qrU0TyNXi3/4ODy/T9bHXZqRY+tLkxDsCvb4Sv0atBxoX34X69g7zm2kkkh8WiWxYG9eRh552ZCGmTH42Fl5xkrCqAAMBwk/wEjo2K20q9jKHIGqWULkwkTcTuXMDAMyQRrjAQwHDelparHTDVtu29Jr3j4aLfr37Px1N0Y8h0YN47zf5ktG7OV3EWkz+hBIAHWz2kc9xKQazgo3099ZrGI2b8YyBeaRkGSI=
