language: node_js
services:
- docker
node_js:
- 10.9.0
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - graphhopper
  - map-matching
  - graph-cache
  - osrm
  - tcat-ny-us
  - node_modules
  - cache
install:
- npm install
- docker-compose -f docker-compose/docker-compose.yml up -d
script:
- npm run travis
env:
  global:
    - PORT=3000
    - REGISTER_TOKEN=REGISTER_TOKEN
    - GHOPPER_BUS=localhost
    - GHOPPER_WALKING=localhost
    - MAP_MATCHING=localhost
    - PLACES_KEY=PLACES_KEY
    - secure: CzAeQtkXaOe6RJaZUBM1ne11SixrCGt1eqCBuouzKniXQ8J/nztNo+s20cbz/gmKVzLzQE61I1Fdjzm/7OzCiCdN1hdGuwwHIo5d9VniHhIXUXTg9UoCUfYu/+CYTKxKulTpBt2GNxdVvWi4j8Honxm3tMrMZS5qlIuHYOo8+iHDUKJpK7Ft7lHAfIGEmNNJCka8Ty6fcWvGxmojHVzuUObUnRv4Q18cFAXSynST+3pO8BexxfSZcE19giLf/fg0z8xaVMTnTs9MfB4ghffjUlDDZRNYa9cU0OKHnIJ0TiU7jOajd2bDToqyo5xsVDa4Kfqt8LeXIMnyKZ5BkgfngswoqhURd9H0q1781lAhiKg3K26xigJJhU89Y2DlTExARX3xrlxINvu5pA88vqeilVgogZHSCLJCoj68DSIJvzZK7HkDVIGloICxDazyFFT5zH8aPXW2s6ob+6Xiqs+swDxu4IYGVfJ6ih1XHUrNKy8nSCFLN1jQnekrcOyZ/RF1atTnSv5vpXZSeXeH+ELTHjGxhwKaJ1HTU1BEIBr4SQRiPYIcv7lRRNfzIBuh9Nfk+bbXNKVT3dLL8u/gO+6pb/Wcq0WCsxzw89sEdQiEn07YEOMhfA9SNIhkyBhMNTfl1N8P3EJc9J4H9f2IY12G/gjA9SA26nqgYS2AIvvkTRk=
