language: node_js
services:
  - docker
node_js:
  - 10.9.0
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.cache
  - $HOME/docker
  - graphhopper
  - map-matching
  - graph-cache
  - osrm
  - tcat-ny-us
  - node_modules
  - cache
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
install:
  - npm run setup
script:
  - npm test
  - npm run stop-ghopper
