version: "3.4"

services:
  node:
    build:
      context: .
      target: development
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  ghopper:
    image: cornellappdev/transit-ghopper:1.2
    ports:
      - "8988:8988"

  map:
    image: cornellappdev/transit-map
    ports:
      - "8989:8989"

  ghopper-walking:
    image: cornellappdev/transit-ghopper-walking:latest
    ports:
      - "8987:8987"

  live-tracking:
    image: cornellappdev/transit-python:cc0c4c048fe66036f3372d47703994ce84eb9317
    env_file: python.env
    ports:
      - "5000:5000"
