services:
  node:
    image: cornellappdev/transit-dev:${IMAGE_TAG}
    env_file: .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  ghopper:
    image: cornellappdev/transit-ghopper:03_01_25
    ports:
      - "8988:8988"

  map:
    image: cornellappdev/transit-map
    ports:
      - "8989:8989"

  ghopper-walking:
    image: cornellappdev/transit-ghopper-walking:latest
    ports:
      - "8987:8987"

  live-tracking:
    image: cornellappdev/transit-python:03_01_25
    env_file: python.envrc
    ports:
      - "5000:5000"
