services:
  node:
    build:
      context: .
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  ghopper:
    image: cornellappdev/transit-ghopper:08_24_24
    ports:
      - "8988:8988"

  map:
    image: cornellappdev/transit-map
    ports:
      - "8989:8989"

  ghopper-walking:
    image: cornellappdev/transit-ghopper-walking:latest
    ports:
      - "8987:8987"

  live-tracking:
    image: cornellappdev/transit-python:latest
    ports:
      - "5000:5000"
