services:
  node:
    image: cornellappdev/transit-dev:${IMAGE_TAG}
    env_file: .env
    volumes:
      - ./service-account-credentials.json:/app/service-account-credentials.json:ro
    ports:
      - "8080:3000"

  python-app:
    image: cornellappdev/transit-python:latest
    ports:
      - "5000:5000"
