version: "3.4"

services:
  node:
    build:
      context: .
      target: development
    env_file: .envrc
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  ghopper:
    image: cornellappdev/transit-ghopper:v1.2.1
    ports:
      - "8988:8988"

  map:
    image: cornellappdev/transit-map
    ports:
      - "8989:8989"

  ghopper-walking:
    image: cornellappdev/transit-ghopper-walking:latest
    ports:
      - "8987:8987"

  live-tracking:
    image: cornellappdev/transit-python:v1.2.2
    env_file: python.envrc
    ports:
      - "5000:5000"
