language: java
services:
  - docker
node_js:
  - "10.9.0"
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.cache
  - graphhopper
  - map-matching
  - graph-cache
  - osrm
  - tcat-ny-us
  - node_modules
  - cache
install:
  - docker-compose -f docker-compose/docker-compose.yml up
script:
  - npm run start-dev
