version: "3.4"

services:
  ghopper:
    image: cornellappdev/transit-ghopper
    ports:
      - "8988:8988"

  ghopper-walking:
    image: cornellappdev/transit-ghopper-walking
    ports:
      - "8987:8987"

  map:
    image: cornellappdev/transit-map
    ports:
      - "8989:8989"

  live-tracking:
    image: cornellappdev/transit-live-tracking
    ports:
      - "5000:5000"
