version: "3.4"

services:
  node:
    build: node
    image: 104.236.60.90:443/transit-node:0.1.3
    env_file: node.env
    ports:
      - "80:3000"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: any

  ghopper:
    build: ghopper
    image: 104.236.60.90:443/transit-ghopper:0.1.2
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: any

  map:
    build: map
    image: 104.236.60.90:443/transit-map:0.1.2
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: any

  ghopper-walking:
    build: ghopper-walking
    image: 104.236.60.90:443/transit-ghopper-walking:0.1.2
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: any
