version: "3.4"

services:
  ghopper:
    build: ghopper
    image: ghopper
    ports:
      - "8988:8988"

  map:
    build: map
    image: map
    ports:
      - "8989:8989"

  ghopper-walking:
    build: ghopper-walking
    image: ghopper-walking
    ports:
      - "8987:8987"
  
  dev-testing:
    build: dev-testing
    image: dev-testing
    ports:
    - "3000:3000"
