name: Docker Build & Push and Deploy to transit-dev

on:
  push:
    branches: [master, autodeploy]
  workflow_dispatch:

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Get SHA
      #   id: vars
      #   run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Docker Build & Push ghopper
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker-compose/ghopper/Dockerfile
          push: true
          tags: cornellappdev/transit-ghopper:latest

      - name: Docker Build & Push ghopper-walking
        uses: docker/build-push-action@v2
        with:
          context: ./usr/src/app/graphhopper-walking/
          file: ./docker-compose/ghopper-walking/Dockerfile
          push: true
          tags: cornellappdev/transit-ghopper-walking:latest

      - name: Docker Build & Push map
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./docker-compose/map/Dockerfile
          push: true
          tags: cornellappdev/transit-map:latest
      # - name: Remote SSH and Deploy
      #   uses: appleboy/ssh-action@master
      #   env:
      #     IMAGE_TAG: ${{ steps.vars.outputs.sha_short }}
      #   with:
      #     host: ${{ secrets.DEV_SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USERNAME }}
      #     key: ${{ secrets.DEV_SERVER_KEY }}
      #     script: |
      #       export IMAGE_TAG=${{ steps.vars.outputs.sha_short }}
      #       cd docker-compose
      #       docker stack rm the-stack
      #       sleep 20s
      #       docker stack deploy -c docker-compose.yml the-stack
      #       yes | docker system prune -a
